# Generated by Django 5.0.6 on 2024-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('max_size', models.IntegerField(default=100)),
                ('current_size', models.IntegerField(default=100)),
                ('image', models.ImageField(upload_to='shimages')),
            ],
        ),
    ]
